### ISSUE TITLE
Fetch mechanism not compatible with all browsers

### ISSUE THREAD

**Issue by rsjazz** [jazz-community/rtc-workitem-bulk-mover-ui#26] opened 2019-07-08 11:05 UTC
Can you have a look at https://jazz.net/forum/questions/264070/plugin-to-move-work-items-between-project-areas-not-working , Lukas?

**Comment by innerjoin** [comment] 2019-07-15 07:41
With [Version 1.4.6](https://github.com/jazz-community/rtc-workitem-bulk-mover-ui/releases/tag/v1.4.6), a new loading mechanism was introduced and along with that, the `fetch` implementation has been replaced. Unfortunately, the chosen library has some severe issues in terms of supporting newer versions of Firefox and Edge. Due to the fact that these issues does not seem to get fixed, a switch of the underlying `fetch` library is required.

_In addition, the question raised brought another point to my attention: The current implementation does not support the whole range of UTF-8. For example, if a project area name is written in Japanese, the name will not be returned properly and therefore the plug-in does not work correctly, see [the respective issue raised](https://github.com/jazz-community/rtc-workitem-bulk-mover-service/issues/13)

**Comment by innerjoin** [comment] 2019-07-16 11:35
Should now be fixed with in [Version 1.5.3](https://github.com/jazz-community/rtc-workitem-bulk-mover-ui/releases/tag/v1.5.3). I will close this issue as soon as I have feedback from _Ian_.

**Comment by innerjoin** [comment] 2019-07-23 11:56
_Ian_ has confirmed that the new release has worked for him. Thank you @rsjazz for pointing me to this issue.

**Closed by innerjoin** 2019-07-23 11:56 UTC
Labels: bug
